[workspace]
members = [
    "nervusdb-core",
    "nervusdb-temporal",
    "bindings/node/native/nervusdb-node",
    "bindings/python/nervusdb-py",
    "bindings/uniffi/nervusdb-uniffi"
]
resolver = "2"
