[package]
name = "nervusdb-rust-test"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
nervusdb = { path = "../../nervusdb" }
nervusdb-query = { path = "../../nervusdb-query" }
tempfile = "3"

[workspace]
