[package]
name = "nervusdb-pyo3"
version = "0.1.0"
edition = "2021"

[lib]
name = "nervusdb"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.6", features = ["extension-module"] }
nervusdb-v2 = { path = "../nervusdb-v2" }
nervusdb-v2-query = { path = "../nervusdb-v2-query" }
